### ISSUE TITLE
[BUG] `help()` references `__signature__`, which does not exist on native_func's.

### ISSUE THREAD

**Issue by ghost** [pocketpy/pocketpy#256]
### Bug description

When calling the `help()` function on a native function, the following error message is printed:

```
  Traceback (most recent call last):
    File "main.py", line 3
      help(somefunc)
    File "<builtins>", line 173, in help
      print(obj.__signature__)
  AttributeError: 'native_func' object has no attribute '__signature__'
```

### Steps to reproduce
- Create a native function
- call `help()` on it

### Environment information

`main` branch, OS not relevant.

### Additional context

I'd be open to implement `__signature__` on `native_func`. Alternatively, the `help()` function could be changed to print the name of the function instead of the signature.

(Also, I realize I reported a few things over the last few days, please let me know if this is ok or if I should stop reporting issues.)

**Comment by blueloveTH** [comment]
Hi. I know this. The current docstring/help system is not fully operational.

Please keep this issue open. I may improve it in the `v2.0` branch.

**Comment by blueloveTH** [comment]
> (Also, I realize I reported a few things over the last few days, please let me know if this is ok or if I should stop reporting issues.)

It is ok. However, I am working on `v2.0` branch. The main branch is going to be frozen. And low priority issues will not be fixed on the main branch. Critical bugs could be fixed on main and then cherry-pick to `v2.0`.

**Comment by blueloveTH** [comment]
Sure! You can help implement this feature in `v2.0`.

## For `native_func`
You can get its name and argc. Assume the name is `f`:
- `argc != -1`, signature could be "f(_0, _1, ..._argc)"
- `argc == -1`, signature is `f(*args, **kwargs)`

There is no docstring support. `__doc__` always returns None.

## For `function`
You need to inspect its `FuncDecl_` to generate its signature. It is a bit complex.

And `__doc__` should return the true docstring.

**Comment by blueloveTH** [comment]
`bind` is our new style bindings API. It creates a `function` object. `bind_func` creates old style `native_func`.

**Comment by blueloveTH** [comment]
I know your game needs a better doc system. There are some defects if you rely on the builtin `help()` (even with future improvements).

Most of the builtin classes and functions do not have any doc. For example, `list` and `dict`. If you want to provide a comprehensive doc system like cpython, you need replace the builtin `help()` with your own one. And you can use a custom database to provide such docs.

**Comment by blueloveTH** [comment]
About `inspect`, currently there is no way to get internal information of pocketpy classes and functions. Because these information are treated as "private". We often change the internal structures with few breaks to user-level functionalities. However, if `inspect` module is provided, such "private" details become public. I cannot ensure it is stable. It is better to do this in user-level.

**Comment by blueloveTH** [comment]
The main task on `v2.0` can be roughly described as follows:
1. do a major refactor to improve overall code quality. Every source file changes.
2. significantly improve memory management (far less gc!)
3. provide a pybind11-compatible bindings API

`v2.0` will be released in 2~3 months. And `v1.x` will be a LTS version. No more features, only bug fixes.

**Comment by blueloveTH** [comment]
If you want to fix v1.x, the correct way is to comment the signature call out or raise `NotImplementedError`. As I said, v1.x accepts bug fixes but not new features. Inspection is in fact a not supported ability.

**Comment by blueloveTH** [comment]
Feel free to fix or patch. However, please keep this issue open and I'd like to improve it on v2 if I have time!
